/*

GUILLOCHÉ PATTERNS [banknotes security patterns]

Guilloché patterns are spirograph-like curves that frame 
a curve within an inner and outer envelope curve. 
They are used on banknotes, securities, and passports 
worldwide for added security against counterfeiting. 

For currency, the precise techniques used by the governments of 
Russia, the United States, Brazil, the European Union, Madagascar, 
Egypt, and all other countries are likely quite different. 

The figures above show the same guilloche pattern plotted in polar 
and Cartesian coordinates generated by a series of nested additions 
and multiplications of sinusoids of various periods.

Guilloché machines (alternately called geometric lathes, rose 
machines, engine-turners, and cycloidal engines) were first used 
for a watch casing dated 1624, and consist of myriad gears and 
settings that can produce many different patterns. Many goldsmiths, 
including Fabergè, employed guilloché machines.

    Basic hypertrochoid equation:
    
    x = (R + r) * cos(theta) + (r + p) * cos ( ((R + r)/r) * theta )
    y = (R + r) * sin(theta) - (r + p) * sin ( ((R + r)/r) * theta )
    
    where theta = 0 ... 2 * PI, R = 50.0; r = -0.25, p = 25.0;
  
  
    Modified hypertrochoid equation:
    
    x = (R + r) * cos(m * theta) + (r + p) * cos(((R+r)/r) * m * theta) + Q * cos(n * theta)
    y = (R + r) * sin(m * theta) - (r + p) * sin(((R+r)/r) * m * theta) + Q * sin(n * theta)
    
    where theta = 0 ... 2 * PI, R = 50.0; r = -0.25, p = 25.0, Q = 3, m = 1, n = 6;
    

REFERENCES:
http://mathworld.wolfram.com/GuillochePattern.html
https://en.wikipedia.org/wiki/Guilloch%C3%A9

http://ministryoftype.co.uk/words/article/guilloches/

APP FOR OSX
http://www.excourse.com/excentro/


@author  Vladimir V. KUCHINOV
@email   helloworld@vkuchinov.co.uk

*/

import java.util.Random;
Random seed = new Random(12345);

Guilloche pattern;

void setup(){
  
     size(750, 750, "processing.core.PGraphicsRetina2D");
     background(0);
     translate(width/2, height/2);
  
     pattern = new Guilloche();
     pattern.draw();
}
